### ISSUE TITLE
peerDependicies not met on install

### ISSUE THREAD

**Issue by derekslenk** [karma-runner/karma-coffee-preprocessor#23]
When trying to install karma and other tests, get the following errors:
npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-junit-reporter@0.0.2 wants karma@~0.9
npm ERR! peerinvalid Peer karma-chrome-launcher@0.1.4 wants karma@>=0.9.3
npm ERR! peerinvalid Peer karma-firefox-launcher@0.1.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-html2js-preprocessor@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-jasmine@0.1.5 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-requirejs@0.2.2 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-script-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-coffee-preprocessor@0.2.1 wants karma@>=0.11.14
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.1.4 wants karma@>=0.9

It works by using 0.1.3 of the preprocessor, but I was wondering if there is another way to get them all installed? 0.1.3 breaks our build server

**Comment by Dignifiedquire** [comment]
Should be fixed in the latest versions
