### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by dakeyras7** [karma-runner/karma-coffee-preprocessor#31]
Hi,

Is there a reason why the loosened coffeescript dependency that was commited to in ed41be726a484e95ac2e6f715f30c89aa9f46c48  has not been packaged and released yet?

Cheers,
T.

**Comment by Dignifiedquire** [comment]
No specific reason, other than that I haven't gotten to it yet

**Comment by Dignifiedquire** [comment]
Fixed in `0.3.0`

**Comment by dakeyras7** [comment]
:+1: thx!
