### ISSUE TITLE
Use your own version of lodash

### ISSUE THREAD

**Issue by arshaw** [karma-runner/karma-coffee-preprocessor#39]
The latest karma (v1.1.1) is throwing a warning with karma-coffee-preprocessor:

```
DEPRECATED: use your own version of lodash, this will go away in karma@2.0
```

and I've pinpointed it to this line:
https://github.com/karma-runner/karma-coffee-preprocessor/blob/v1.0.0/index.js#L27

Could you change it so that lodash is a proper dependency?

**Comment by avindra** [comment]
@dignifiedquire @arshaw : Already fixed in https://github.com/karma-runner/karma-coffee-preprocessor/pull/38

**Comment by dignifiedquire** [comment]
Hahah, I forgot I merged that one already, better cut a release then
